version: '3'
services:
  remotedev:
    build: .
    env_file: .env
    ports:
        - '127.0.0.1:8000:8000'
    links:
      - db
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - '27017:27017'
